home/urls.py
from django.urls import path

from home.views import home, add

app_name = 'home'
urlpatterns = [
    path("", home, name="home"),
    path("add/", add, name="add")
]

smallapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls"), name="home")
]

home/models.py
from django.db import models


class Data(models.Model):
    data = models.CharField(max_length=255)

home/views.py
import string
import random
import os

from django.shortcuts import render, redirect

# Create your views here.
from home.models import Data


def home(request):
    items = Data.objects.all()
    return render(request, "home.html", {"items": items, "host": os.uname()[1]})

def add(request):
    random_text = ''.join([random.choice(string.ascii_letters + string.digits) for n in range(32)])
    data = Data(data=random_text)
    data.save()
    return redirect("/")

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>A really small app</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Small App</a>
    </nav>
    <h2>Hostname : {{ host }}</h2>
    <div class="container">
        <table class="table table-striped">
        <thead>
        <tr>
                <th>ID</th>
                <th>Text</th>
            </tr>
        </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.id }}</td>
                    <td>{{ item.data }}</td>
                </tr>
            {% endfor %}
        </tbody>
        </table>
        <a class="btn btn-primary" href="{% url "home:add" %}">Random data</a>
    </div>
</body>
</html>